apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-example
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      type: backend
      service: python
  template:
    metadata:
      labels:
        type: backend
        service: python
    spec:
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
