apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
  selector:
    type: backend
    service: python
