apiVersion: v1
kind: Service
metadata:
  name: flask-example-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
  selector:
    type: backend
    service: python
